---

- name: create container on proxmox host
  proxmox:
    vmid: "{{ proxmox_vmid }}"
    node: "{{ proxmox_node }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_host }}"
    password: "{{ proxmox_password_root }}"
    hostname: "{{ proxmox_hostname }}"
    ostemplate: "{{ proxmox_ostemplate }}"
    storage: "{{ proxmox_storage|default('local-zfs') }}"
    unprivileged: "{{ proxmox_enable_docker|default(false) }}"
    onboot: "{{ proxmox_onboot|default(True) }}"
    memory: "{{ proxmox_memory }}"
    disk: "{{ proxmox_disk }}"
    cores: "{{ proxmox_cores }}"
    cpus: "{{ proxmox_cpus }}"
    netif: '{"net0":"name=eth0,hwaddr={{ proxmox_hwaddr }},ip={{ proxmox_ip }}/{{ proxmox_ip_mask }},gw={{ proxmox_network_gateway }},bridge={{ proxmox_network_bridge }}"}'
    mounts: "{{ proxmox_secondary_mounts|default('{}') }}"
    pubkey: "{{ proxmox_authorized_keys_root }}"
    timeout: 180
  notify:
    - enable and install sshd
    - enable features for Docker in container
    - wait for container to be up
    - upgrade all packages to latest

- name: start container
  proxmox:
    vmid: "{{ proxmox_vmid }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_host }}"
    state: started
    timeout: 90

# - name: upgrade all packages to latest
#   delegate_to: "{{ proxmox_ip|default(ansible_host) }}"
#   yum:
#     name: '*'
#     state: latest
#     update_cache: true
